fix: use flathub api

diff --git a/.github/workflows/validate-flatpaks.yml b/.github/workflows/validate-flatpaks.yml
--- a/.github/workflows/validate-flatpaks.yml
+++ b/.github/workflows/validate-flatpaks.yml
@@ -13,25 +13,30 @@ jobs:
       - name: Checkout
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
 
-      - name: Set up Flathub
+      - name: Get Flathub apps
         shell: bash
         run: |
-          sudo apt install -y flatpak
-          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
+          FLATHUB_LIST=$(mktemp)
+          curl -X 'GET' \
+            'https://flathub.org/api/v2/appstream?filter=apps' \
+            -H 'accept: application/json' | jq -r ".[]" >> "${FLATHUB_LIST}"
 
-      - name: Validate Flatpaks
-        shell: bash
-        run: |
-          echo "Validating flatpak files in flatpaks/ directory..."
+          curl -X 'GET' \
+            'https://flathub.org/api/v2/appstream?filter=runtime' \
+            -H 'accept: application/json' | jq -r ".[]" >> "${FLATHUB_LIST}"
 
           set -xeuo pipefail
 
-          find "flatpaks" -iname '*\.list*' -print0 | \
-            while IFS= read -r -d '' flatpaks_file ; do \
+          find "flatpaks" -iname '*.list*' -print0 | \
+            while IFS= read -r -d '' flatpaks_file; do
               echo "::group:: ===$(basename "$flatpaks_file")==="
-              grep -v "#.*" "$flatpaks_file" | \
-                while read -r flatpak ; do \
-                  flatpak remote-info --user flathub "${flatpak}"
-                done
+              grep -vE '^#' "$flatpaks_file" | while read -r flatpak; do
+                # Only output on errors
+                if ! grep -Fxq "$flatpak" "$FLATHUB_LIST"; then
+                  echo "$flatpak NOT found on Flathub"
+                fi
+              done
+
               echo "::endgroup::"
             done
+
